### ISSUE TITLE
Can't login twice with new login/password

### ISSUE THREAD

**Issue by ya5iu** [TheAmazingRak/py-librus-api#2]
When I try to login twice with different login/password the second try always fails because header used in second attempt is set by the first one and the "Authorization" header contains token from previous login.
 
Example:
librus1 = Librus()
librus1.login(login, password)
librus1.logged_in <- is true
librus2 = Librus()
librus2.login(login1, password1)
librus2.logged_in <- is always false

To solve the problem I have extended Librus class and reset headers:

class LibrusExt(Librus):

    def __init__(self):
        self.headers = {
            "Authorization": "Basic Mjg6ODRmZGQzYTg3YjAzZDNlYTZmZmU3NzdiNThiMzMyYjE="
        }

**Comment by lomber1** [comment]
I'm going to fix this issue in next update (probably [0.3.2])
BTW thank you for even trying to use this package. I'm really surprised that someone found this project and I'm even more surprised that someone used it and found and issue!

**Comment by lomber1** [comment]
@ya5iu Checkout new branch that contains fix for this issue, you can test it if it works as expected. I cannot do this because I have access to only one account.
